// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	notf "github.com/So-ham/Content-Moderation/pkg/grpc/clients/notf"
)

// NotfServiceServer is an autogenerated mock type for the NotfServiceServer type
type NotfServiceServer struct {
	mock.Mock
}

// SendFlaggedNotification provides a mock function with given fields: _a0, _a1
func (_m *NotfServiceServer) SendFlaggedNotification(_a0 context.Context, _a1 *notf.SendFlaggedNotificationReq) (*emptypb.Empty, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SendFlaggedNotification")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *notf.SendFlaggedNotificationReq) (*emptypb.Empty, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *notf.SendFlaggedNotificationReq) *emptypb.Empty); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *notf.SendFlaggedNotificationReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedNotfServiceServer provides a mock function with no fields
func (_m *NotfServiceServer) mustEmbedUnimplementedNotfServiceServer() {
	_m.Called()
}

// NewNotfServiceServer creates a new instance of NotfServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotfServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotfServiceServer {
	mock := &NotfServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
