// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeNotfServiceServer is an autogenerated mock type for the UnsafeNotfServiceServer type
type UnsafeNotfServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedNotfServiceServer provides a mock function with no fields
func (_m *UnsafeNotfServiceServer) mustEmbedUnimplementedNotfServiceServer() {
	_m.Called()
}

// NewUnsafeNotfServiceServer creates a new instance of UnsafeNotfServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeNotfServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeNotfServiceServer {
	mock := &UnsafeNotfServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
