apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-moderation-deployment
spec:
  replicas: 1  # You can increase this number for scaling
  selector:
    matchLabels:
      app: content-moderation
  template:
    metadata:
      labels:
        app: content-moderation
    spec:
      containers:
      - name: content-moderation-container
        image: 9874694577/moderation-service:${{ github.sha }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080  # The port your app listens on inside the container
        envFrom:
        - configMapRef:
            name: moderation-config
        - secretRef:
            name: moderation-secrets
