apiVersion: v1
kind: Service
metadata:
  name: content-moderation-service
spec:
  selector:
    app: content-moderation  # This matches the label from the deployment
  ports:
    - protocol: TCP
      port: 80   # The port exposed by the service
      targetPort: 8080  # The port that your container listens on
  type: LoadBalancer  # For cloud-based LoadBalancer. Change to NodePort for local Minikube setup
