name: Build, Push Docker Image, and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 9874694577/moderation-service:${{ github.sha }}

      # Authenticate with Google Cloud using service account key
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up kubectl to interact with your GKE cluster
      # - name: Set up kubectl
      #   run: |
      #     gcloud container clusters get-credentials autopilot-cluster-1 --location asia-south1 --project eternal-respect-455817-q2
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: autopilot-cluster-1
          location: asia-south1

      # Apply Kubernetes deployment and service from the kubernetes folder
      - name: Apply Kubernetes deployment and service
        run: |
          kubectl apply -f kubernetes/deployment.yaml --validate=false
          kubectl apply -f kubernetes/service.yaml --validate=false

      # Deploy to GKE
      - name: Deploy to GKE
        run: |
          kubectl set image deployment/content-moderation-deployment content-moderation-container=9874694577/moderation-service:${{ github.sha }}
          kubectl rollout status deployment/content-moderation-deployment
